name: 'Comment on PR'
description: 'Programatically comment on a PR within an action'
inputs:
  message:  # input message
    description: 'Text to write'
    required: true
    default: ''
  check-for-duplicates:
    description: "If false, action doesn't check for duplicate msg"
    required: false
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
